export type ColorShade = 'red' | 'yellow' | 'green' | 'blue' | 'violet' | 'white' | 'black' | 'brown';
export type Color = {
	shade: ColorShade;
};
export type HtmlColors = {
	[key: string]: Color;
}
export type MmrColors = {
	[key: string]: string;
}
export const mmrColors: MmrColors = {
	'DEFAULT': 'var(--charcoal-text, #393b3f)',
	'red': '#9a2802',
	'orange': '#9a2802',
	'yellow': 'var(--sun-400-background, #ffb957)',
	'green': 'var(--forest-500-text, #286230)',
	'blue': 'var(--royal-500-text, #1b3273)',
	'violet': 'var(--lavendar-500-text, #57418e)',
	'brown': 'var(--charcoal-text, #393b3f)',
	'black': 'var(--charcoal-text, #393b3f)',
	'grey': 'var(--charcoal-text, #393b3f)',
	'white': 'var(--charcoal-text, #393b3f)',

	'var(--charcoal-text, #393b3f)': '#393b3f',
	'var(--lavendar-500-text, #57418e)': '#57418e',
	'var(--royal-500-text, #1b3273)': '#1b3273',
	'var(--forest-500-text, #286230)': '#286230',
	'var(--sun-400-background, #ffb957)': '#ffb957'
}
export const htmlColors: HtmlColors = {
	pink: { shade: 'red'},
	lightpink: { shade: 'red'},
	hotpink: { shade: 'red'},
	deeppink: { shade: 'red'},
	palevioletred: { shade: 'red'},
	mediumvioletred: { shade: 'red'},
	lightsalmon: { shade: 'red'},
	salmon: { shade: 'red'},
	darksalmon: { shade: 'red'},
	lightcoral: { shade: 'red'},
	indianred: { shade: 'red'},
	crimson: { shade: 'red'},
	firebrick: { shade: 'red'},
	darkred: { shade: 'red'},
	red: { shade: 'red'},
	orangered: { shade: 'red'},
	tomato: { shade: 'red'},
	coral: { shade: 'red'},
	darkorange: { shade: 'red'},
	orange: { shade: 'red'},

	yellow: { shade: 'yellow'},
	lightyellow: { shade: 'yellow'},
	lemonchiffon: { shade: 'yellow'},
	lightgoldenrodyellow: { shade: 'yellow'},
	papayawhip: { shade: 'yellow'},
	moccasin: { shade: 'yellow'},
	peachpuff: { shade: 'yellow'},
	palegoldenrod: { shade: 'yellow'},
	khaki: { shade: 'yellow'},
	darkkhaki: { shade: 'yellow'},
	gold: { shade: 'yellow'},

	cornsilk: { shade: 'yellow'},
	blanchedalmond: { shade: 'yellow'},
	bisque: { shade: 'yellow'},
	navajowhite: { shade: 'yellow'},
	wheat: { shade: 'yellow'},
	burlywood: { shade: 'yellow'},
	tan: { shade: 'brown' },
	rosybrown: { shade: 'brown' },
	sandybrown: { shade: 'brown' },
	goldenrod: { shade: 'brown' },
	darkgoldenrod: { shade: 'brown' },
	peru: { shade: 'brown' },
	chocolate: { shade: 'brown' },
	saddlebrown: { shade: 'brown' },
	sienna: { shade: 'brown' },
	brown: { shade: 'brown' },
	maroon: { shade: 'brown' },
	darkolivegreen: { shade: 'green' },
	olive: { shade: 'green' },
	olivedrab: { shade: 'green' },
	yellowgreen: { shade: 'green' },
	limegreen: { shade: 'green' },
	lime: { shade: 'green' },
	lawngreen: { shade: 'green' },
	chartreuse: { shade: 'green' },
	greenyellow: { shade: 'green' },
	springgreen: { shade: 'green' },
	mediumspringgreen: { shade: 'green' },
	lightgreen: { shade: 'green' },
	palegreen: { shade: 'green' },
	darkseagreen: { shade: 'green' },
	mediumseagreen: { shade: 'green' },
	seagreen: { shade: 'green' },
	forestgreen: { shade: 'green' },
	green: { shade: 'green' },
	darkgreen: { shade: 'green' },
	mediumaquamarine: { shade: 'green' },
	aqua: { shade: 'blue' },
	cyan: { shade: 'blue' },
	lightcyan: { shade: 'blue' },
	paleturquoise: { shade: 'blue' },
	aquamarine: { shade: 'blue' },
	turquoise: { shade: 'blue' },
	mediumturquoise: { shade: 'blue' },
	darkturquoise: { shade: 'blue' },
	lightseagreen: { shade: 'blue' },
	cadetblue: { shade: 'blue' },
	darkcyan: { shade: 'blue' },
	teal: { shade: 'blue' },
	lightsteelblue: { shade: 'blue' },
	powderblue: { shade: 'blue' },
	lightblue: { shade: 'blue' },
	skyblue: { shade: 'blue' },
	lightskyblue: { shade: 'blue' },
	deepskyblue: { shade: 'blue' },
	dodgerblue: { shade: 'blue' },
	cornflowerblue: { shade: 'blue' },
	steelblue: { shade: 'blue' },
	royalblue: { shade: 'blue' },
	blue: { shade: 'blue' },
	mediumblue: { shade: 'blue' },
	darkblue: { shade: 'blue' },
	navy: { shade: 'blue' },
	midnightblue: { shade: 'blue' },
	lavender: { shade: 'violet' },
	thistle: { shade: 'violet' },
	plum: { shade: 'violet' },
	violet: { shade: 'violet' },
	orchid: { shade: 'violet' },
	fuchsia: { shade: 'violet' },
	magenta: { shade: 'violet' },
	mediumorchid: { shade: 'violet' },
	mediumpurple: { shade: 'violet' },
	blueviolet: { shade: 'violet' },
	darkviolet: { shade: 'violet' },
	darkorchid: { shade: 'violet' },
	darkmagenta: { shade: 'violet' },
	purple: { shade: 'violet' },
	indigo: { shade: 'violet' },
	darkslateblue: { shade: 'violet' },
	rebeccapurple: { shade: 'violet' },
	slateblue: { shade: 'violet' },
	mediumslateblue: { shade: 'violet' },
	white: { shade: 'white' },
	snow: { shade: 'white' },
	honeydew: { shade: 'white' },
	mintcream: { shade: 'white' },
	azure: { shade: 'white' },
	aliceblue: { shade: 'white' },
	ghostwhite: { shade: 'white' },
	whitesmoke: { shade: 'white' },
	seashell: { shade: 'white' },
	beige: { shade: 'white' },
	oldlace: { shade: 'white' },
	floralwhite: { shade: 'white' },
	ivory: { shade: 'white' },
	antiquewhite: { shade: 'white' },
	linen: { shade: 'white' },
	lavenderblush: { shade: 'white' },
	mistyrose: { shade: 'white' },
	gainsboro: { shade: 'black' },
	lightgrey: { shade: 'black' },
	silver: { shade: 'black' },
	darkgray: { shade: 'black' },
	gray: { shade: 'black' },
	grey: { shade: 'black' },
	dimgray: { shade: 'black' },
	lightslategray: { shade: 'black' },
	slategray: { shade: 'black' },
	darkslategray: { shade: 'black' },
	black: { shade: 'black' },
}
